version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - node -v
      - npm -v
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:staging
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: dist
