version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - rm -rf /etc/apt/sources.list.d/google-chrome.list
      - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - curl -fsSL https://deb.nodesource.com/setup_15.x | bash -
      - apt-get update
      - apt-get install nodejs -y -q
      - mv /usr/local/bin/node /usr/local/bin/node14
      - mv /usr/local/bin/npm /usr/local/bin/npm6
      - mv /usr/bin/node /usr/local/bin/node
      - npm install -g npm
      - node -v
      - npm -v
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:staging
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: dist
