version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 15.14.0
    commands:
      - npm install npm@7.7.6 -g
      - npm set progress=false
  pre_build:
    commands:
      - npm install
      - npm run lint
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist