version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - npm install -g browserstack-cypress-cli
  build:
    commands:
      - mkdir -p ./e2e_tests/log
      - touch ./e2e_tests/log/browserstack.log
      - BROWSERSTACK_LOCAL=true
      - VITE_APP_ALGOLIA_APP_ID=${VUE_APP_ALGOLIA_APP_ID} VITE_APP_ALGOLIA_API_READ_KEY=${VUE_APP_ALGOLIA_API_READ_KEY} VITE_APP_ALGOLIA_INDEX=${VUE_APP_ALGOLIA_INDEX} VITE_APP_ALGOLIA_INDEX_WORD_COUNT_REPLICA=${VUE_APP_ALGOLIA_INDEX_WORD_COUNT_REPLICA} VITE_APP_ALGOLIA_INDEX_LAST_UPDATED_REPLICA=${VUE_APP_ALGOLIA_INDEX_LAST_UPDATED_REPLICA} npm run dev
      - browserstack-cypress run --sync --username ${BROWSERSTACK_USER} --key ${BROWSERSTACK_ACCESS_KEY} --local-identifier BrowserStackPipeline
reports:
  browserstack-reports:
    files:
      - '**/*'
    base-directory: ./e2e_tests/output
    file-format: JunitXml