version: 0.2
phases:
  pre_build:
    commands:
      - npm install
      - npm install -g browserstack-cypress-cli
  build:
    commands:
      - mkdir -p ./results
      - mkdir -p ./log
      - BROWSERSTACK_LOCAL=true
      - VITE_ALGOLIA_APP_ID=${VITE_ALGOLIA_APP_ID} VITE_ALGOLIA_API_READ_KEY=${VITE_ALGOLIA_API_READ_KEY} VITE_ALGOLIA_INDEX=${VITE_ALGOLIA_INDEX} VITE_ALGOLIA_INDEX_WORD_COUNT_REPLICA=${VITE_ALGOLIA_INDEX_WORD_COUNT_REPLICA} VITE_ALGOLIA_INDEX_LAST_UPDATED_REPLICA=${VITE_ALGOLIA_INDEX_LAST_UPDATED_REPLICA} npm run dev & npm run test:ci
reports:
  browserstack-reports:
    files:
      - '**/*'
    base-directory: ./e2e_tests/output
    file-format: JunitXml