name: Lint & build assets

on:
  push:
    branches: [ dev, production ]
  pull_request:
    branches: [ dev, production ]

jobs:
  lint-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '16', '18' ]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          node -v
          npm ci

      - name: Lint
        run: npm run lint

      - name: Build assets
        run: npm run build --if-present